# coding: utf-8

"""
    WP Toolkit API

    ### REST API documentation & sandbox usage instructions  ### Initial setup  #### Plesk 1. Open 'Tools & Settings' > 'Remote API (REST)' > 'WP Toolkit REST API' 2. In the 'Servers' dropdown choose 'Public API endpoint for Plesk' 3. Specify the IP address or the hostname of your server in the 'host' field and click 'Authorize': - 3a. Provide username and password in the 'httpBasic' section, click 'Authorize', then 'Close' - 3b. Fill out the 'pleskApiToken' field, click 'Authorize', then 'Close'  #### WHM & cPanel 1. Open WP Toolkit > 'Global Settings' > 'Open REST API documentation' 2. In the 'Servers' dropdown choose 'Public API endpoint for WHM' 3. Specify the IP address or the hostname of your server in the 'host' field 4. Insert your current session identifier (in '/cpsessXXXXX' format) in the 'cpanelOrWhmSecurityToken' field. You can copy this identifier from the browser address bar 5. Click 'Authorize', provide username and password in the 'httpBasic' section, click 'Authorize', then 'Close'  **Note**: *session identifier is not required for sending external requests to WP Toolkit REST API, it is needed only for this sandbox*  ### How to perform an API request 1. Choose an API resource from the list, click on it to expand, and click 'Try it out' 2. Prefill the fields with corresponding data and click 'Execute'. If a field is not marked as requried, you can leave it empty 3. Scroll down the page to see the results of API request execution

    The version of the OpenAPI document: 6.6.5-9203
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from plesk_wp_toolkit_client.models.clone_stub_response import CloneStubResponse

class TestCloneStubResponse(unittest.TestCase):
    """CloneStubResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CloneStubResponse:
        """Test CloneStubResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CloneStubResponse`
        """
        model = CloneStubResponse()
        if include_optional:
            return CloneStubResponse(
                value = plesk_wp_toolkit_client.models.clone_stub_response_value.CloneStubResponse_value(
                    database = plesk_wp_toolkit_client.models.clone_stub_database_response.CloneStubDatabaseResponse(
                        value = plesk_wp_toolkit_client.models.clone_stub_database_response_value.CloneStubDatabaseResponse_value(
                            name = plesk_wp_toolkit_client.models.clone_stub_database_response_value_name.CloneStubDatabaseResponse_value_name(
                                value = 'wp_pfexo', 
                                meta = plesk_wp_toolkit_client.models.clone_stub_database_response_value_name_meta.CloneStubDatabaseResponse_value_name_meta(
                                    creation_allowed = True, ), ), 
                            name_prefix = plesk_wp_toolkit_client.models.clone_stub_database_response_value_name_prefix.CloneStubDatabaseResponse_value_namePrefix(
                                value = 'wpt_', ), 
                            server = plesk_wp_toolkit_client.models.clone_stub_database_response_value_server.CloneStubDatabaseResponse_value_server(
                                value = '1', 
                                meta = plesk_wp_toolkit_client.models.clone_stub_database_response_value_server_meta.CloneStubDatabaseResponse_value_server_meta(
                                    choices = [
                                        plesk_wp_toolkit_client.models.parameter_with_choices_meta_choices_inner.ParameterWithChoices_meta_choices_inner(
                                            value = '', 
                                            title = '', )
                                        ], ), ), ), ), 
                    domain = plesk_wp_toolkit_client.models.clone_stub_domain_response.CloneStubDomainResponse(
                        value = plesk_wp_toolkit_client.models.clone_stub_domain_response_value.CloneStubDomainResponse_value(
                            existing = plesk_wp_toolkit_client.models.clone_stub_domain_response_value_existing.CloneStubDomainResponse_value_existing(
                                value = 'example.com', 
                                meta = plesk_wp_toolkit_client.models.clone_stub_domain_response_value_existing_meta.CloneStubDomainResponse_value_existing_meta(
                                    choices = [
                                        plesk_wp_toolkit_client.models.parameter_with_choices_meta_choices_inner.ParameterWithChoices_meta_choices_inner(
                                            value = '', 
                                            title = '', )
                                        ], 
                                    document_root = '/var/www/vhosts/example.com/httpdocs', ), ), 
                            new_subdomain = plesk_wp_toolkit_client.models.clone_stub_new_subdomain_response.CloneStubNewSubdomainResponse(
                                value = plesk_wp_toolkit_client.models.clone_stub_new_subdomain_response_value.CloneStubNewSubdomainResponse_value(
                                    name = plesk_wp_toolkit_client.models.clone_stub_new_subdomain_response_value_name.CloneStubNewSubdomainResponse_value_name(
                                        value = 'staging', ), 
                                    parent_domain = plesk_wp_toolkit_client.models.clone_stub_new_subdomain_response_value_parent_domain.CloneStubNewSubdomainResponse_value_parentDomain(
                                        value = 'example.com', 
                                        meta = plesk_wp_toolkit_client.models.clone_stub_database_response_value_server_meta.CloneStubDatabaseResponse_value_server_meta(
                                            choices = , ), ), ), ), ), ), 
                    installation_path = plesk_wp_toolkit_client.models.clone_stub_installation_path_response.CloneStubInstallationPathResponse(
                        value = 'wordpress-clone', ), ),
                meta = plesk_wp_toolkit_client.models.clone_stub_response_meta.CloneStubResponse_meta(
                    messages = plesk_wp_toolkit_client.models.clone_stub_messages_response.CloneStubMessagesResponse(
                        multisite_on_subdomains_unix = plesk_wp_toolkit_client.models.clone_stub_messages_response_multisite_on_subdomains_unix.CloneStubMessagesResponse_multisiteOnSubdomainsUnix(
                            text = 'This WordPress installation is a subdomain-based multisite installation. We will update (if needed) DNS zones and additional Apache or Nginx settings of target domain to use wildcard subdomains.', 
                            intent = 'warning', ), 
                        multisite_on_subdomains_windows = plesk_wp_toolkit_client.models.clone_stub_messages_response_multisite_on_subdomains_windows.CloneStubMessagesResponse_multisiteOnSubdomainsWindows(
                            text = 'This WordPress installation is a subdomain-based multisite installation. After the installation is cloned, you must configure the environment (IIS sites binding) manually.', 
                            intent = 'warning', ), 
                        multisite_on_subdirectories_windows = plesk_wp_toolkit_client.models.clone_stub_messages_response_multisite_on_subdirectories_windows.CloneStubMessagesResponse_multisiteOnSubdirectoriesWindows(
                            text = 'This WordPress installation is a directory-based multisite installation. After the installation is cloned, you must configure the environment (IIS sites binding, web.config settings) manually.', 
                            intent = 'warning', ), 
                        unable_to_check_database = plesk_wp_toolkit_client.models.clone_stub_messages_response_unable_to_check_database.CloneStubMessagesResponse_unableToCheckDatabase(
                            text = 'Warning: mysqlcheck utility has detected some issues with the database of the source WordPress installation. You can find the details below. Continue the cloning if you think these issues will not affect the cloning procedure.', 
                            intent = 'warning', ), ), )
            )
        else:
            return CloneStubResponse(
                value = plesk_wp_toolkit_client.models.clone_stub_response_value.CloneStubResponse_value(
                    database = plesk_wp_toolkit_client.models.clone_stub_database_response.CloneStubDatabaseResponse(
                        value = plesk_wp_toolkit_client.models.clone_stub_database_response_value.CloneStubDatabaseResponse_value(
                            name = plesk_wp_toolkit_client.models.clone_stub_database_response_value_name.CloneStubDatabaseResponse_value_name(
                                value = 'wp_pfexo', 
                                meta = plesk_wp_toolkit_client.models.clone_stub_database_response_value_name_meta.CloneStubDatabaseResponse_value_name_meta(
                                    creation_allowed = True, ), ), 
                            name_prefix = plesk_wp_toolkit_client.models.clone_stub_database_response_value_name_prefix.CloneStubDatabaseResponse_value_namePrefix(
                                value = 'wpt_', ), 
                            server = plesk_wp_toolkit_client.models.clone_stub_database_response_value_server.CloneStubDatabaseResponse_value_server(
                                value = '1', 
                                meta = plesk_wp_toolkit_client.models.clone_stub_database_response_value_server_meta.CloneStubDatabaseResponse_value_server_meta(
                                    choices = [
                                        plesk_wp_toolkit_client.models.parameter_with_choices_meta_choices_inner.ParameterWithChoices_meta_choices_inner(
                                            value = '', 
                                            title = '', )
                                        ], ), ), ), ), 
                    domain = plesk_wp_toolkit_client.models.clone_stub_domain_response.CloneStubDomainResponse(
                        value = plesk_wp_toolkit_client.models.clone_stub_domain_response_value.CloneStubDomainResponse_value(
                            existing = plesk_wp_toolkit_client.models.clone_stub_domain_response_value_existing.CloneStubDomainResponse_value_existing(
                                value = 'example.com', 
                                meta = plesk_wp_toolkit_client.models.clone_stub_domain_response_value_existing_meta.CloneStubDomainResponse_value_existing_meta(
                                    choices = [
                                        plesk_wp_toolkit_client.models.parameter_with_choices_meta_choices_inner.ParameterWithChoices_meta_choices_inner(
                                            value = '', 
                                            title = '', )
                                        ], 
                                    document_root = '/var/www/vhosts/example.com/httpdocs', ), ), 
                            new_subdomain = plesk_wp_toolkit_client.models.clone_stub_new_subdomain_response.CloneStubNewSubdomainResponse(
                                value = plesk_wp_toolkit_client.models.clone_stub_new_subdomain_response_value.CloneStubNewSubdomainResponse_value(
                                    name = plesk_wp_toolkit_client.models.clone_stub_new_subdomain_response_value_name.CloneStubNewSubdomainResponse_value_name(
                                        value = 'staging', ), 
                                    parent_domain = plesk_wp_toolkit_client.models.clone_stub_new_subdomain_response_value_parent_domain.CloneStubNewSubdomainResponse_value_parentDomain(
                                        value = 'example.com', 
                                        meta = plesk_wp_toolkit_client.models.clone_stub_database_response_value_server_meta.CloneStubDatabaseResponse_value_server_meta(
                                            choices = , ), ), ), ), ), ), 
                    installation_path = plesk_wp_toolkit_client.models.clone_stub_installation_path_response.CloneStubInstallationPathResponse(
                        value = 'wordpress-clone', ), ),
                meta = plesk_wp_toolkit_client.models.clone_stub_response_meta.CloneStubResponse_meta(
                    messages = plesk_wp_toolkit_client.models.clone_stub_messages_response.CloneStubMessagesResponse(
                        multisite_on_subdomains_unix = plesk_wp_toolkit_client.models.clone_stub_messages_response_multisite_on_subdomains_unix.CloneStubMessagesResponse_multisiteOnSubdomainsUnix(
                            text = 'This WordPress installation is a subdomain-based multisite installation. We will update (if needed) DNS zones and additional Apache or Nginx settings of target domain to use wildcard subdomains.', 
                            intent = 'warning', ), 
                        multisite_on_subdomains_windows = plesk_wp_toolkit_client.models.clone_stub_messages_response_multisite_on_subdomains_windows.CloneStubMessagesResponse_multisiteOnSubdomainsWindows(
                            text = 'This WordPress installation is a subdomain-based multisite installation. After the installation is cloned, you must configure the environment (IIS sites binding) manually.', 
                            intent = 'warning', ), 
                        multisite_on_subdirectories_windows = plesk_wp_toolkit_client.models.clone_stub_messages_response_multisite_on_subdirectories_windows.CloneStubMessagesResponse_multisiteOnSubdirectoriesWindows(
                            text = 'This WordPress installation is a directory-based multisite installation. After the installation is cloned, you must configure the environment (IIS sites binding, web.config settings) manually.', 
                            intent = 'warning', ), 
                        unable_to_check_database = plesk_wp_toolkit_client.models.clone_stub_messages_response_unable_to_check_database.CloneStubMessagesResponse_unableToCheckDatabase(
                            text = 'Warning: mysqlcheck utility has detected some issues with the database of the source WordPress installation. You can find the details below. Continue the cloning if you think these issues will not affect the cloning procedure.', 
                            intent = 'warning', ), ), ),
        )
        """

    def testCloneStubResponse(self):
        """Test CloneStubResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
