# coding: utf-8

"""
    WP Toolkit API

    ### REST API documentation & sandbox usage instructions  ### Initial setup  #### Plesk 1. Open 'Tools & Settings' > 'Remote API (REST)' > 'WP Toolkit REST API' 2. In the 'Servers' dropdown choose 'Public API endpoint for Plesk' 3. Specify the IP address or the hostname of your server in the 'host' field and click 'Authorize': - 3a. Provide username and password in the 'httpBasic' section, click 'Authorize', then 'Close' - 3b. Fill out the 'pleskApiToken' field, click 'Authorize', then 'Close'  #### WHM & cPanel 1. Open WP Toolkit > 'Global Settings' > 'Open REST API documentation' 2. In the 'Servers' dropdown choose 'Public API endpoint for WHM' 3. Specify the IP address or the hostname of your server in the 'host' field 4. Insert your current session identifier (in '/cpsessXXXXX' format) in the 'cpanelOrWhmSecurityToken' field. You can copy this identifier from the browser address bar 5. Click 'Authorize', provide username and password in the 'httpBasic' section, click 'Authorize', then 'Close'  **Note**: *session identifier is not required for sending external requests to WP Toolkit REST API, it is needed only for this sandbox*  ### How to perform an API request 1. Choose an API resource from the list, click on it to expand, and click 'Try it out' 2. Prefill the fields with corresponding data and click 'Execute'. If a field is not marked as requried, you can leave it empty 3. Scroll down the page to see the results of API request execution

    The version of the OpenAPI document: 6.6.5-9203
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from plesk_wp_toolkit_client.models.installation_backup_meta_value import InstallationBackupMetaValue

class TestInstallationBackupMetaValue(unittest.TestCase):
    """InstallationBackupMetaValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InstallationBackupMetaValue:
        """Test InstallationBackupMetaValue
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InstallationBackupMetaValue`
        """
        model = InstallationBackupMetaValue()
        if include_optional:
            return InstallationBackupMetaValue(
                file_name = plesk_wp_toolkit_client.models.installation_backup_meta_value_file_name.InstallationBackupMeta_value_fileName(
                    value = 'domain.tld__2023-05-31T15_56_29+0000.zip', 
                    meta = plesk_wp_toolkit_client.models.meta.meta(), ),
                file_size = plesk_wp_toolkit_client.models.installation_backup_meta_value_file_size.InstallationBackupMeta_value_fileSize(
                    value = 40285, 
                    meta = plesk_wp_toolkit_client.models.meta.meta(), ),
                created_at = plesk_wp_toolkit_client.models.installation_backup_meta_value_created_at.InstallationBackupMeta_value_createdAt(
                    value = '2023-05-31T14:20:30+00:00', 
                    meta = plesk_wp_toolkit_client.models.meta.meta(), ),
                absolute_file_path = plesk_wp_toolkit_client.models.installation_backup_meta_value_absolute_file_path.InstallationBackupMeta_value_absoluteFilePath(
                    value = '/path/to/file/archive', 
                    meta = plesk_wp_toolkit_client.models.meta.meta(), )
            )
        else:
            return InstallationBackupMetaValue(
                file_name = plesk_wp_toolkit_client.models.installation_backup_meta_value_file_name.InstallationBackupMeta_value_fileName(
                    value = 'domain.tld__2023-05-31T15_56_29+0000.zip', 
                    meta = plesk_wp_toolkit_client.models.meta.meta(), ),
                file_size = plesk_wp_toolkit_client.models.installation_backup_meta_value_file_size.InstallationBackupMeta_value_fileSize(
                    value = 40285, 
                    meta = plesk_wp_toolkit_client.models.meta.meta(), ),
                created_at = plesk_wp_toolkit_client.models.installation_backup_meta_value_created_at.InstallationBackupMeta_value_createdAt(
                    value = '2023-05-31T14:20:30+00:00', 
                    meta = plesk_wp_toolkit_client.models.meta.meta(), ),
                absolute_file_path = plesk_wp_toolkit_client.models.installation_backup_meta_value_absolute_file_path.InstallationBackupMeta_value_absoluteFilePath(
                    value = '/path/to/file/archive', 
                    meta = plesk_wp_toolkit_client.models.meta.meta(), ),
        )
        """

    def testInstallationBackupMetaValue(self):
        """Test InstallationBackupMetaValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
