# coding: utf-8

"""
    WP Toolkit API

    ### REST API documentation & sandbox usage instructions  ### Initial setup  #### Plesk 1. Open 'Tools & Settings' > 'Remote API (REST)' > 'WP Toolkit REST API' 2. In the 'Servers' dropdown choose 'Public API endpoint for Plesk' 3. Specify the IP address or the hostname of your server in the 'host' field and click 'Authorize': - 3a. Provide username and password in the 'httpBasic' section, click 'Authorize', then 'Close' - 3b. Fill out the 'pleskApiToken' field, click 'Authorize', then 'Close'  #### WHM & cPanel 1. Open WP Toolkit > 'Global Settings' > 'Open REST API documentation' 2. In the 'Servers' dropdown choose 'Public API endpoint for WHM' 3. Specify the IP address or the hostname of your server in the 'host' field 4. Insert your current session identifier (in '/cpsessXXXXX' format) in the 'cpanelOrWhmSecurityToken' field. You can copy this identifier from the browser address bar 5. Click 'Authorize', provide username and password in the 'httpBasic' section, click 'Authorize', then 'Close'  **Note**: *session identifier is not required for sending external requests to WP Toolkit REST API, it is needed only for this sandbox*  ### How to perform an API request 1. Choose an API resource from the list, click on it to expand, and click 'Try it out' 2. Prefill the fields with corresponding data and click 'Execute'. If a field is not marked as requried, you can leave it empty 3. Scroll down the page to see the results of API request execution

    The version of the OpenAPI document: 6.6.5-9203
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from plesk_wp_toolkit_client.models.clone_stub_database_response_value_server import CloneStubDatabaseResponseValueServer

class TestCloneStubDatabaseResponseValueServer(unittest.TestCase):
    """CloneStubDatabaseResponseValueServer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CloneStubDatabaseResponseValueServer:
        """Test CloneStubDatabaseResponseValueServer
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CloneStubDatabaseResponseValueServer`
        """
        model = CloneStubDatabaseResponseValueServer()
        if include_optional:
            return CloneStubDatabaseResponseValueServer(
                value = '1',
                meta = plesk_wp_toolkit_client.models.clone_stub_database_response_value_server_meta.CloneStubDatabaseResponse_value_server_meta(
                    choices = [
                        plesk_wp_toolkit_client.models.parameter_with_choices_meta_choices_inner.ParameterWithChoices_meta_choices_inner(
                            value = '', 
                            title = '', )
                        ], )
            )
        else:
            return CloneStubDatabaseResponseValueServer(
                value = '1',
                meta = plesk_wp_toolkit_client.models.clone_stub_database_response_value_server_meta.CloneStubDatabaseResponse_value_server_meta(
                    choices = [
                        plesk_wp_toolkit_client.models.parameter_with_choices_meta_choices_inner.ParameterWithChoices_meta_choices_inner(
                            value = '', 
                            title = '', )
                        ], ),
        )
        """

    def testCloneStubDatabaseResponseValueServer(self):
        """Test CloneStubDatabaseResponseValueServer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
