# coding: utf-8

"""
    WP Toolkit API

    ### REST API documentation & sandbox usage instructions  ### Initial setup  #### Plesk 1. Open 'Tools & Settings' > 'Remote API (REST)' > 'WP Toolkit REST API' 2. In the 'Servers' dropdown choose 'Public API endpoint for Plesk' 3. Specify the IP address or the hostname of your server in the 'host' field and click 'Authorize': - 3a. Provide username and password in the 'httpBasic' section, click 'Authorize', then 'Close' - 3b. Fill out the 'pleskApiToken' field, click 'Authorize', then 'Close'  #### WHM & cPanel 1. Open WP Toolkit > 'Global Settings' > 'Open REST API documentation' 2. In the 'Servers' dropdown choose 'Public API endpoint for WHM' 3. Specify the IP address or the hostname of your server in the 'host' field 4. Insert your current session identifier (in '/cpsessXXXXX' format) in the 'cpanelOrWhmSecurityToken' field. You can copy this identifier from the browser address bar 5. Click 'Authorize', provide username and password in the 'httpBasic' section, click 'Authorize', then 'Close'  **Note**: *session identifier is not required for sending external requests to WP Toolkit REST API, it is needed only for this sandbox*  ### How to perform an API request 1. Choose an API resource from the list, click on it to expand, and click 'Try it out' 2. Prefill the fields with corresponding data and click 'Execute'. If a field is not marked as requried, you can leave it empty 3. Scroll down the page to see the results of API request execution

    The version of the OpenAPI document: 6.6.5-9203
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from plesk_wp_toolkit_client.models.word_press_updates_response import WordPressUpdatesResponse

class TestWordPressUpdatesResponse(unittest.TestCase):
    """WordPressUpdatesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WordPressUpdatesResponse:
        """Test WordPressUpdatesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `WordPressUpdatesResponse`
        """
        model = WordPressUpdatesResponse()
        if include_optional:
            return WordPressUpdatesResponse(
                id = 1,
                applicable = True,
                display_title = 'example.tld/wordpress',
                title = 'My Awesome WordPress',
                multisite = True,
                vulnerable = True,
                last_check_update_timestamp = 56,
                smart_update = plesk_wp_toolkit_client.models.word_press_updates_smart_updates_response.WordPressUpdatesSmartUpdatesResponse(
                    status = True, 
                    task_status = 'started', 
                    applicable = True, ),
                core = plesk_wp_toolkit_client.models.word_press_updates_response_core.WordPressUpdatesResponse_core(
                    version = '6.0.0', 
                    available_version = '6.0.1', 
                    restore_point = plesk_wp_toolkit_client.models.installation_restore_point.InstallationRestorePoint(
                        available = True, 
                        restore_point_timestamp = 1640008056, 
                        previous_version = '4.9.1', 
                        version = '5.1.0', 
                        error_message = 'Some error was occurred', 
                        display_timestamp = 'Dec 20, 2021 08:47 PM', 
                        full_snapshot = True, 
                        message = 'Message for snapshot tooltip', 
                        source_url = 'https://source.tld', ), ),
                plugins = [
                    plesk_wp_toolkit_client.models.installation_plugin.InstallationPlugin(
                        slug = 'super-awesome-plugin', 
                        title = 'Super awesome plugin', 
                        description = 'Used by millions... It makes your site awesome...', 
                        version = '1.0.1', 
                        available_version = '1.1.0', 
                        status = True, 
                        must_use = False, 
                        auto_updates = True, 
                        auto_updates_available = True, 
                        vulnerable = False, 
                        change_log_url = 'https://www.wordpress.org/plugins/super-awesome-plugin', )
                    ],
                themes = [
                    plesk_wp_toolkit_client.models.installation_theme.InstallationTheme(
                        slug = 'super-awesome-theme', 
                        title = 'Super awesome theme', 
                        description = 'Used by millions... It makes your site awesome...', 
                        version = '1.0.1', 
                        available_version = '1.1.0', 
                        status = True, 
                        auto_updates = True, 
                        auto_updates_available = True, 
                        vulnerable = False, 
                        change_log_url = 'https://www.wordpress.org/themes/super-awesome-theme', )
                    ],
                auto_update = plesk_wp_toolkit_client.models.installation_auto_update_response.InstallationAutoUpdateResponse(
                    available = True, 
                    safe_update = True, 
                    core = 'major', 
                    plugins = plesk_wp_toolkit_client.models.installation_plugins_settings_response.InstallationPluginsSettingsResponse(
                        force_updates = False, 
                        newly_installed_updates = False, 
                        update_vulnerable = False, 
                        deactivate_vulnerable = False, ), 
                    themes = plesk_wp_toolkit_client.models.installation_themes_settings_response.InstallationThemesSettingsResponse(
                        force_updates = False, 
                        newly_installed_updates = False, 
                        update_vulnerable = False, ), ),
                tasks = {"update":{"id":1,"code":"task\\updateitems","title":"Updating selected items...","status":"running","progress":0,"steps":[],"publicParams":{"currentlyUpdatingInstallationId":2,"successfullyUpdatedInstallationsIds":[1]},"errors":[]},"check":{"id":1,"code":"mass-check-updates","title":"Checking for updates","status":"running","progress":0,"steps":[],"publicParams":{"installationsIds":[1,2]},"errors":[]}}
            )
        else:
            return WordPressUpdatesResponse(
                id = 1,
                applicable = True,
                display_title = 'example.tld/wordpress',
                title = 'My Awesome WordPress',
                multisite = True,
                vulnerable = True,
                last_check_update_timestamp = 56,
                smart_update = plesk_wp_toolkit_client.models.word_press_updates_smart_updates_response.WordPressUpdatesSmartUpdatesResponse(
                    status = True, 
                    task_status = 'started', 
                    applicable = True, ),
                core = plesk_wp_toolkit_client.models.word_press_updates_response_core.WordPressUpdatesResponse_core(
                    version = '6.0.0', 
                    available_version = '6.0.1', 
                    restore_point = plesk_wp_toolkit_client.models.installation_restore_point.InstallationRestorePoint(
                        available = True, 
                        restore_point_timestamp = 1640008056, 
                        previous_version = '4.9.1', 
                        version = '5.1.0', 
                        error_message = 'Some error was occurred', 
                        display_timestamp = 'Dec 20, 2021 08:47 PM', 
                        full_snapshot = True, 
                        message = 'Message for snapshot tooltip', 
                        source_url = 'https://source.tld', ), ),
                plugins = [
                    plesk_wp_toolkit_client.models.installation_plugin.InstallationPlugin(
                        slug = 'super-awesome-plugin', 
                        title = 'Super awesome plugin', 
                        description = 'Used by millions... It makes your site awesome...', 
                        version = '1.0.1', 
                        available_version = '1.1.0', 
                        status = True, 
                        must_use = False, 
                        auto_updates = True, 
                        auto_updates_available = True, 
                        vulnerable = False, 
                        change_log_url = 'https://www.wordpress.org/plugins/super-awesome-plugin', )
                    ],
                themes = [
                    plesk_wp_toolkit_client.models.installation_theme.InstallationTheme(
                        slug = 'super-awesome-theme', 
                        title = 'Super awesome theme', 
                        description = 'Used by millions... It makes your site awesome...', 
                        version = '1.0.1', 
                        available_version = '1.1.0', 
                        status = True, 
                        auto_updates = True, 
                        auto_updates_available = True, 
                        vulnerable = False, 
                        change_log_url = 'https://www.wordpress.org/themes/super-awesome-theme', )
                    ],
                auto_update = plesk_wp_toolkit_client.models.installation_auto_update_response.InstallationAutoUpdateResponse(
                    available = True, 
                    safe_update = True, 
                    core = 'major', 
                    plugins = plesk_wp_toolkit_client.models.installation_plugins_settings_response.InstallationPluginsSettingsResponse(
                        force_updates = False, 
                        newly_installed_updates = False, 
                        update_vulnerable = False, 
                        deactivate_vulnerable = False, ), 
                    themes = plesk_wp_toolkit_client.models.installation_themes_settings_response.InstallationThemesSettingsResponse(
                        force_updates = False, 
                        newly_installed_updates = False, 
                        update_vulnerable = False, ), ),
                tasks = {"update":{"id":1,"code":"task\\updateitems","title":"Updating selected items...","status":"running","progress":0,"steps":[],"publicParams":{"currentlyUpdatingInstallationId":2,"successfullyUpdatedInstallationsIds":[1]},"errors":[]},"check":{"id":1,"code":"mass-check-updates","title":"Checking for updates","status":"running","progress":0,"steps":[],"publicParams":{"installationsIds":[1,2]},"errors":[]}},
        )
        """

    def testWordPressUpdatesResponse(self):
        """Test WordPressUpdatesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
