# coding: utf-8

"""
    WP Toolkit API

    ### REST API documentation & sandbox usage instructions  ### Initial setup  #### Plesk 1. Open 'Tools & Settings' > 'Remote API (REST)' > 'WP Toolkit REST API' 2. In the 'Servers' dropdown choose 'Public API endpoint for Plesk' 3. Specify the IP address or the hostname of your server in the 'host' field and click 'Authorize': - 3a. Provide username and password in the 'httpBasic' section, click 'Authorize', then 'Close' - 3b. Fill out the 'pleskApiToken' field, click 'Authorize', then 'Close'  #### WHM & cPanel 1. Open WP Toolkit > 'Global Settings' > 'Open REST API documentation' 2. In the 'Servers' dropdown choose 'Public API endpoint for WHM' 3. Specify the IP address or the hostname of your server in the 'host' field 4. Insert your current session identifier (in '/cpsessXXXXX' format) in the 'cpanelOrWhmSecurityToken' field. You can copy this identifier from the browser address bar 5. Click 'Authorize', provide username and password in the 'httpBasic' section, click 'Authorize', then 'Close'  **Note**: *session identifier is not required for sending external requests to WP Toolkit REST API, it is needed only for this sandbox*  ### How to perform an API request 1. Choose an API resource from the list, click on it to expand, and click 'Try it out' 2. Prefill the fields with corresponding data and click 'Execute'. If a field is not marked as requried, you can leave it empty 3. Scroll down the page to see the results of API request execution

    The version of the OpenAPI document: 6.6.5-9203
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501

import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictInt, StrictStr
from typing import Optional
from typing_extensions import Annotated
from plesk_wp_toolkit_client.models.background_task_with_url_response import BackgroundTaskWithUrlResponse
from plesk_wp_toolkit_client.models.clone_path_validator_request import ClonePathValidatorRequest
from plesk_wp_toolkit_client.models.clone_stub_response import CloneStubResponse
from plesk_wp_toolkit_client.models.installation_clone_request import InstallationCloneRequest

from plesk_wp_toolkit_client.api_client import ApiClient, RequestSerialized
from plesk_wp_toolkit_client.api_response import ApiResponse
from plesk_wp_toolkit_client.rest import RESTResponseType


class InstallationsFeaturesCloneApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def clone_installation(
        self,
        installation_clone_request: InstallationCloneRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> BackgroundTaskWithUrlResponse:
        """clone_installation

        Clone WordPress installation

        :param installation_clone_request: (required)
        :type installation_clone_request: InstallationCloneRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._clone_installation_serialize(
            installation_clone_request=installation_clone_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '201': "BackgroundTaskWithUrlResponse",
            '400': "BadRequestResponse",
            '401': "UnauthorizedResponse",
            '404': "NotFoundResponse",
            '422': "UnprocessableEntityResponse",
            '500': "InternalServerErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def clone_installation_with_http_info(
        self,
        installation_clone_request: InstallationCloneRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[BackgroundTaskWithUrlResponse]:
        """clone_installation

        Clone WordPress installation

        :param installation_clone_request: (required)
        :type installation_clone_request: InstallationCloneRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._clone_installation_serialize(
            installation_clone_request=installation_clone_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '201': "BackgroundTaskWithUrlResponse",
            '400': "BadRequestResponse",
            '401': "UnauthorizedResponse",
            '404': "NotFoundResponse",
            '422': "UnprocessableEntityResponse",
            '500': "InternalServerErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def clone_installation_without_preload_content(
        self,
        installation_clone_request: InstallationCloneRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """clone_installation

        Clone WordPress installation

        :param installation_clone_request: (required)
        :type installation_clone_request: InstallationCloneRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._clone_installation_serialize(
            installation_clone_request=installation_clone_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '201': "BackgroundTaskWithUrlResponse",
            '400': "BadRequestResponse",
            '401': "UnauthorizedResponse",
            '404': "NotFoundResponse",
            '422': "UnprocessableEntityResponse",
            '500': "InternalServerErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _clone_installation_serialize(
        self,
        installation_clone_request,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter
        if installation_clone_request is not None:
            _body_params = installation_clone_request


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'httpBasic', 
            'pleskApiToken'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/v1/cloner',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def get_clone_stub(
        self,
        installation_id: Annotated[StrictInt, Field(description="Installation ID")],
        database_name: Annotated[Optional[StrictStr], Field(description="Database name")] = None,
        database_server: Annotated[Optional[StrictStr], Field(description="Database server ID (Plesk only)")] = None,
        domain_existing: Annotated[Optional[StrictStr], Field(description="Domain name")] = None,
        domain_new_subdomain_name: Annotated[Optional[StrictStr], Field(description="Subdomain name")] = None,
        domain_new_subdomain_parent_domain: Annotated[Optional[StrictStr], Field(description="Domain name")] = None,
        installation_path: Annotated[Optional[StrictStr], Field(description="Installation path of cloned WordPress site (relative to the root directory of the domain)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> CloneStubResponse:
        """get_clone_stub

        Get default cloning options

        :param installation_id: Installation ID (required)
        :type installation_id: int
        :param database_name: Database name
        :type database_name: str
        :param database_server: Database server ID (Plesk only)
        :type database_server: str
        :param domain_existing: Domain name
        :type domain_existing: str
        :param domain_new_subdomain_name: Subdomain name
        :type domain_new_subdomain_name: str
        :param domain_new_subdomain_parent_domain: Domain name
        :type domain_new_subdomain_parent_domain: str
        :param installation_path: Installation path of cloned WordPress site (relative to the root directory of the domain)
        :type installation_path: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_clone_stub_serialize(
            installation_id=installation_id,
            database_name=database_name,
            database_server=database_server,
            domain_existing=domain_existing,
            domain_new_subdomain_name=domain_new_subdomain_name,
            domain_new_subdomain_parent_domain=domain_new_subdomain_parent_domain,
            installation_path=installation_path,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CloneStubResponse",
            '400': "BadRequestResponse",
            '404': "NotFoundResponse",
            '500': "InternalServerErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def get_clone_stub_with_http_info(
        self,
        installation_id: Annotated[StrictInt, Field(description="Installation ID")],
        database_name: Annotated[Optional[StrictStr], Field(description="Database name")] = None,
        database_server: Annotated[Optional[StrictStr], Field(description="Database server ID (Plesk only)")] = None,
        domain_existing: Annotated[Optional[StrictStr], Field(description="Domain name")] = None,
        domain_new_subdomain_name: Annotated[Optional[StrictStr], Field(description="Subdomain name")] = None,
        domain_new_subdomain_parent_domain: Annotated[Optional[StrictStr], Field(description="Domain name")] = None,
        installation_path: Annotated[Optional[StrictStr], Field(description="Installation path of cloned WordPress site (relative to the root directory of the domain)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[CloneStubResponse]:
        """get_clone_stub

        Get default cloning options

        :param installation_id: Installation ID (required)
        :type installation_id: int
        :param database_name: Database name
        :type database_name: str
        :param database_server: Database server ID (Plesk only)
        :type database_server: str
        :param domain_existing: Domain name
        :type domain_existing: str
        :param domain_new_subdomain_name: Subdomain name
        :type domain_new_subdomain_name: str
        :param domain_new_subdomain_parent_domain: Domain name
        :type domain_new_subdomain_parent_domain: str
        :param installation_path: Installation path of cloned WordPress site (relative to the root directory of the domain)
        :type installation_path: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_clone_stub_serialize(
            installation_id=installation_id,
            database_name=database_name,
            database_server=database_server,
            domain_existing=domain_existing,
            domain_new_subdomain_name=domain_new_subdomain_name,
            domain_new_subdomain_parent_domain=domain_new_subdomain_parent_domain,
            installation_path=installation_path,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CloneStubResponse",
            '400': "BadRequestResponse",
            '404': "NotFoundResponse",
            '500': "InternalServerErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def get_clone_stub_without_preload_content(
        self,
        installation_id: Annotated[StrictInt, Field(description="Installation ID")],
        database_name: Annotated[Optional[StrictStr], Field(description="Database name")] = None,
        database_server: Annotated[Optional[StrictStr], Field(description="Database server ID (Plesk only)")] = None,
        domain_existing: Annotated[Optional[StrictStr], Field(description="Domain name")] = None,
        domain_new_subdomain_name: Annotated[Optional[StrictStr], Field(description="Subdomain name")] = None,
        domain_new_subdomain_parent_domain: Annotated[Optional[StrictStr], Field(description="Domain name")] = None,
        installation_path: Annotated[Optional[StrictStr], Field(description="Installation path of cloned WordPress site (relative to the root directory of the domain)")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """get_clone_stub

        Get default cloning options

        :param installation_id: Installation ID (required)
        :type installation_id: int
        :param database_name: Database name
        :type database_name: str
        :param database_server: Database server ID (Plesk only)
        :type database_server: str
        :param domain_existing: Domain name
        :type domain_existing: str
        :param domain_new_subdomain_name: Subdomain name
        :type domain_new_subdomain_name: str
        :param domain_new_subdomain_parent_domain: Domain name
        :type domain_new_subdomain_parent_domain: str
        :param installation_path: Installation path of cloned WordPress site (relative to the root directory of the domain)
        :type installation_path: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_clone_stub_serialize(
            installation_id=installation_id,
            database_name=database_name,
            database_server=database_server,
            domain_existing=domain_existing,
            domain_new_subdomain_name=domain_new_subdomain_name,
            domain_new_subdomain_parent_domain=domain_new_subdomain_parent_domain,
            installation_path=installation_path,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "CloneStubResponse",
            '400': "BadRequestResponse",
            '404': "NotFoundResponse",
            '500': "InternalServerErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_clone_stub_serialize(
        self,
        installation_id,
        database_name,
        database_server,
        domain_existing,
        domain_new_subdomain_name,
        domain_new_subdomain_parent_domain,
        installation_path,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if installation_id is not None:
            _path_params['installationId'] = installation_id
        # process the query parameters
        if database_name is not None:
            
            _query_params.append(('database[name]', database_name))
            
        if database_server is not None:
            
            _query_params.append(('database[server]', database_server))
            
        if domain_existing is not None:
            
            _query_params.append(('domain[existing]', domain_existing))
            
        if domain_new_subdomain_name is not None:
            
            _query_params.append(('domain[newSubdomain][name]', domain_new_subdomain_name))
            
        if domain_new_subdomain_parent_domain is not None:
            
            _query_params.append(('domain[newSubdomain][parentDomain]', domain_new_subdomain_parent_domain))
            
        if installation_path is not None:
            
            _query_params.append(('installationPath', installation_path))
            
        # process the header parameters
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'httpBasic', 
            'pleskApiToken'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v1/installations/{installationId}/features/clone/stub',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def validate_clone_path(
        self,
        installation_id: Annotated[StrictInt, Field(description="Installation ID")],
        clone_path_validator_request: ClonePathValidatorRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> None:
        """validate_clone_path

        Validate installation path of a WordPress site clone on domain

        :param installation_id: Installation ID (required)
        :type installation_id: int
        :param clone_path_validator_request: (required)
        :type clone_path_validator_request: ClonePathValidatorRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._validate_clone_path_serialize(
            installation_id=installation_id,
            clone_path_validator_request=clone_path_validator_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '204': None,
            '400': "BadRequestResponse",
            '404': "NotFoundResponse",
            '422': "UnprocessableEntityResponse",
            '500': "InternalServerErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def validate_clone_path_with_http_info(
        self,
        installation_id: Annotated[StrictInt, Field(description="Installation ID")],
        clone_path_validator_request: ClonePathValidatorRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[None]:
        """validate_clone_path

        Validate installation path of a WordPress site clone on domain

        :param installation_id: Installation ID (required)
        :type installation_id: int
        :param clone_path_validator_request: (required)
        :type clone_path_validator_request: ClonePathValidatorRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._validate_clone_path_serialize(
            installation_id=installation_id,
            clone_path_validator_request=clone_path_validator_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '204': None,
            '400': "BadRequestResponse",
            '404': "NotFoundResponse",
            '422': "UnprocessableEntityResponse",
            '500': "InternalServerErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def validate_clone_path_without_preload_content(
        self,
        installation_id: Annotated[StrictInt, Field(description="Installation ID")],
        clone_path_validator_request: ClonePathValidatorRequest,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """validate_clone_path

        Validate installation path of a WordPress site clone on domain

        :param installation_id: Installation ID (required)
        :type installation_id: int
        :param clone_path_validator_request: (required)
        :type clone_path_validator_request: ClonePathValidatorRequest
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._validate_clone_path_serialize(
            installation_id=installation_id,
            clone_path_validator_request=clone_path_validator_request,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '204': None,
            '400': "BadRequestResponse",
            '404': "NotFoundResponse",
            '422': "UnprocessableEntityResponse",
            '500': "InternalServerErrorResponse",
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _validate_clone_path_serialize(
        self,
        installation_id,
        clone_path_validator_request,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if installation_id is not None:
            _path_params['installationId'] = installation_id
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter
        if clone_path_validator_request is not None:
            _body_params = clone_path_validator_request


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'httpBasic', 
            'pleskApiToken'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/v1/installations/{installationId}/features/clone/path-validator',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


