# coding: utf-8

"""
    WP Toolkit API

    ### REST API documentation & sandbox usage instructions  ### Initial setup  #### Plesk 1. Open 'Tools & Settings' > 'Remote API (REST)' > 'WP Toolkit REST API' 2. In the 'Servers' dropdown choose 'Public API endpoint for Plesk' 3. Specify the IP address or the hostname of your server in the 'host' field and click 'Authorize': - 3a. Provide username and password in the 'httpBasic' section, click 'Authorize', then 'Close' - 3b. Fill out the 'pleskApiToken' field, click 'Authorize', then 'Close'  #### WHM & cPanel 1. Open WP Toolkit > 'Global Settings' > 'Open REST API documentation' 2. In the 'Servers' dropdown choose 'Public API endpoint for WHM' 3. Specify the IP address or the hostname of your server in the 'host' field 4. Insert your current session identifier (in '/cpsessXXXXX' format) in the 'cpanelOrWhmSecurityToken' field. You can copy this identifier from the browser address bar 5. Click 'Authorize', provide username and password in the 'httpBasic' section, click 'Authorize', then 'Close'  **Note**: *session identifier is not required for sending external requests to WP Toolkit REST API, it is needed only for this sandbox*  ### How to perform an API request 1. Choose an API resource from the list, click on it to expand, and click 'Try it out' 2. Prefill the fields with corresponding data and click 'Execute'. If a field is not marked as requried, you can leave it empty 3. Scroll down the page to see the results of API request execution

    The version of the OpenAPI document: 6.6.5-9203
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from plesk_wp_toolkit_client.models.admin_settings import AdminSettings
from plesk_wp_toolkit_client.models.auto_update_settings import AutoUpdateSettings
from plesk_wp_toolkit_client.models.database_settings import DatabaseSettings
from plesk_wp_toolkit_client.models.installation_stub_response_installation_path import InstallationStubResponseInstallationPath
from plesk_wp_toolkit_client.models.installation_stub_response_title import InstallationStubResponseTitle
from plesk_wp_toolkit_client.models.parameter_with_choices import ParameterWithChoices
from typing import Optional, Set
from typing_extensions import Self

class InstallationStubResponse(BaseModel):
    """
    InstallationStubResponse
    """ # noqa: E501
    admin: AdminSettings
    database: DatabaseSettings
    protocol: ParameterWithChoices
    title: InstallationStubResponseTitle
    installation_path: InstallationStubResponseInstallationPath = Field(alias="installationPath")
    auto_update: AutoUpdateSettings = Field(alias="autoUpdate")
    language: ParameterWithChoices
    domain: ParameterWithChoices
    version: ParameterWithChoices
    set: ParameterWithChoices
    __properties: ClassVar[List[str]] = ["admin", "database", "protocol", "title", "installationPath", "autoUpdate", "language", "domain", "version", "set"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InstallationStubResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of admin
        if self.admin:
            _dict['admin'] = self.admin.to_dict()
        # override the default output from pydantic by calling `to_dict()` of database
        if self.database:
            _dict['database'] = self.database.to_dict()
        # override the default output from pydantic by calling `to_dict()` of protocol
        if self.protocol:
            _dict['protocol'] = self.protocol.to_dict()
        # override the default output from pydantic by calling `to_dict()` of title
        if self.title:
            _dict['title'] = self.title.to_dict()
        # override the default output from pydantic by calling `to_dict()` of installation_path
        if self.installation_path:
            _dict['installationPath'] = self.installation_path.to_dict()
        # override the default output from pydantic by calling `to_dict()` of auto_update
        if self.auto_update:
            _dict['autoUpdate'] = self.auto_update.to_dict()
        # override the default output from pydantic by calling `to_dict()` of language
        if self.language:
            _dict['language'] = self.language.to_dict()
        # override the default output from pydantic by calling `to_dict()` of domain
        if self.domain:
            _dict['domain'] = self.domain.to_dict()
        # override the default output from pydantic by calling `to_dict()` of version
        if self.version:
            _dict['version'] = self.version.to_dict()
        # override the default output from pydantic by calling `to_dict()` of set
        if self.set:
            _dict['set'] = self.set.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InstallationStubResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "admin": AdminSettings.from_dict(obj["admin"]) if obj.get("admin") is not None else None,
            "database": DatabaseSettings.from_dict(obj["database"]) if obj.get("database") is not None else None,
            "protocol": ParameterWithChoices.from_dict(obj["protocol"]) if obj.get("protocol") is not None else None,
            "title": InstallationStubResponseTitle.from_dict(obj["title"]) if obj.get("title") is not None else None,
            "installationPath": InstallationStubResponseInstallationPath.from_dict(obj["installationPath"]) if obj.get("installationPath") is not None else None,
            "autoUpdate": AutoUpdateSettings.from_dict(obj["autoUpdate"]) if obj.get("autoUpdate") is not None else None,
            "language": ParameterWithChoices.from_dict(obj["language"]) if obj.get("language") is not None else None,
            "domain": ParameterWithChoices.from_dict(obj["domain"]) if obj.get("domain") is not None else None,
            "version": ParameterWithChoices.from_dict(obj["version"]) if obj.get("version") is not None else None,
            "set": ParameterWithChoices.from_dict(obj["set"]) if obj.get("set") is not None else None
        })
        return _obj


