# coding: utf-8

"""
    WP Toolkit API

    ### REST API documentation & sandbox usage instructions  ### Initial setup  #### Plesk 1. Open 'Tools & Settings' > 'Remote API (REST)' > 'WP Toolkit REST API' 2. In the 'Servers' dropdown choose 'Public API endpoint for Plesk' 3. Specify the IP address or the hostname of your server in the 'host' field and click 'Authorize': - 3a. Provide username and password in the 'httpBasic' section, click 'Authorize', then 'Close' - 3b. Fill out the 'pleskApiToken' field, click 'Authorize', then 'Close'  #### WHM & cPanel 1. Open WP Toolkit > 'Global Settings' > 'Open REST API documentation' 2. In the 'Servers' dropdown choose 'Public API endpoint for WHM' 3. Specify the IP address or the hostname of your server in the 'host' field 4. Insert your current session identifier (in '/cpsessXXXXX' format) in the 'cpanelOrWhmSecurityToken' field. You can copy this identifier from the browser address bar 5. Click 'Authorize', provide username and password in the 'httpBasic' section, click 'Authorize', then 'Close'  **Note**: *session identifier is not required for sending external requests to WP Toolkit REST API, it is needed only for this sandbox*  ### How to perform an API request 1. Choose an API resource from the list, click on it to expand, and click 'Try it out' 2. Prefill the fields with corresponding data and click 'Execute'. If a field is not marked as requried, you can leave it empty 3. Scroll down the page to see the results of API request execution

    The version of the OpenAPI document: 6.6.5-9203
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from plesk_wp_toolkit_client.models.installation_admin_settings_request import InstallationAdminSettingsRequest
from plesk_wp_toolkit_client.models.installation_auto_update_request import InstallationAutoUpdateRequest
from plesk_wp_toolkit_client.models.installation_database_settings_request import InstallationDatabaseSettingsRequest
from typing import Optional, Set
from typing_extensions import Self

class InstallationRequest(BaseModel):
    """
    InstallationRequest
    """ # noqa: E501
    domain: StrictStr = Field(description="Domain name")
    installation_path: Optional[StrictStr] = Field(default=None, description="Installation path relative to the root directory of the domain", alias="installationPath")
    language: Optional[StrictStr] = Field(default=None, description="Website language")
    overwrite: Optional[StrictBool] = Field(default=None, description="Overwrite installation")
    protocol: Optional[StrictStr] = Field(default=None, description="Communication protocol")
    set: Optional[StrictInt] = Field(default=None, description="Set ID")
    title: Optional[StrictStr] = Field(default=None, description="Website title")
    version: Optional[StrictStr] = Field(default=None, description="WordPress version")
    admin: Optional[InstallationAdminSettingsRequest] = None
    database: Optional[InstallationDatabaseSettingsRequest] = None
    auto_update: Optional[InstallationAutoUpdateRequest] = Field(default=None, alias="autoUpdate")
    show_domain_overview_link_on_done: Optional[StrictBool] = Field(default=None, description="Show domain overview link in background task", alias="showDomainOverviewLinkOnDone")
    __properties: ClassVar[List[str]] = ["domain", "installationPath", "language", "overwrite", "protocol", "set", "title", "version", "admin", "database", "autoUpdate", "showDomainOverviewLinkOnDone"]

    @field_validator('protocol')
    def protocol_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['http', 'https']):
            raise ValueError("must be one of enum values ('http', 'https')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InstallationRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of admin
        if self.admin:
            _dict['admin'] = self.admin.to_dict()
        # override the default output from pydantic by calling `to_dict()` of database
        if self.database:
            _dict['database'] = self.database.to_dict()
        # override the default output from pydantic by calling `to_dict()` of auto_update
        if self.auto_update:
            _dict['autoUpdate'] = self.auto_update.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InstallationRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "domain": obj.get("domain"),
            "installationPath": obj.get("installationPath"),
            "language": obj.get("language"),
            "overwrite": obj.get("overwrite"),
            "protocol": obj.get("protocol"),
            "set": obj.get("set"),
            "title": obj.get("title"),
            "version": obj.get("version"),
            "admin": InstallationAdminSettingsRequest.from_dict(obj["admin"]) if obj.get("admin") is not None else None,
            "database": InstallationDatabaseSettingsRequest.from_dict(obj["database"]) if obj.get("database") is not None else None,
            "autoUpdate": InstallationAutoUpdateRequest.from_dict(obj["autoUpdate"]) if obj.get("autoUpdate") is not None else None,
            "showDomainOverviewLinkOnDone": obj.get("showDomainOverviewLinkOnDone")
        })
        return _obj


