# coding: utf-8

"""
    WP Toolkit API

    ### REST API documentation & sandbox usage instructions  ### Initial setup  #### Plesk 1. Open 'Tools & Settings' > 'Remote API (REST)' > 'WP Toolkit REST API' 2. In the 'Servers' dropdown choose 'Public API endpoint for Plesk' 3. Specify the IP address or the hostname of your server in the 'host' field and click 'Authorize': - 3a. Provide username and password in the 'httpBasic' section, click 'Authorize', then 'Close' - 3b. Fill out the 'pleskApiToken' field, click 'Authorize', then 'Close'  #### WHM & cPanel 1. Open WP Toolkit > 'Global Settings' > 'Open REST API documentation' 2. In the 'Servers' dropdown choose 'Public API endpoint for WHM' 3. Specify the IP address or the hostname of your server in the 'host' field 4. Insert your current session identifier (in '/cpsessXXXXX' format) in the 'cpanelOrWhmSecurityToken' field. You can copy this identifier from the browser address bar 5. Click 'Authorize', provide username and password in the 'httpBasic' section, click 'Authorize', then 'Close'  **Note**: *session identifier is not required for sending external requests to WP Toolkit REST API, it is needed only for this sandbox*  ### How to perform an API request 1. Choose an API resource from the list, click on it to expand, and click 'Try it out' 2. Prefill the fields with corresponding data and click 'Execute'. If a field is not marked as requried, you can leave it empty 3. Scroll down the page to see the results of API request execution

    The version of the OpenAPI document: 6.6.5-9203
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from plesk_wp_toolkit_client.models.installation_smart_php_updates import InstallationSmartPhpUpdates
from plesk_wp_toolkit_client.models.installation_smart_updates import InstallationSmartUpdates
from typing import Optional, Set
from typing_extensions import Self

class InstallationUpdates(BaseModel):
    """
    InstallationUpdates
    """ # noqa: E501
    applicable: StrictBool = Field(description="Updates might be disabled by the server administrator")
    auto_updates_available: StrictBool = Field(description="Autoupdates availability status", alias="autoUpdatesAvailable")
    available_version: Optional[StrictStr] = Field(description="Version of available update", alias="availableVersion")
    amount_of_plugins_with_updates: StrictInt = Field(description="Number of plugins with available updates", alias="amountOfPluginsWithUpdates")
    amount_of_themes_with_updates: StrictInt = Field(description="Number of themes with available updates", alias="amountOfThemesWithUpdates")
    smart: InstallationSmartUpdates
    php: InstallationSmartPhpUpdates
    __properties: ClassVar[List[str]] = ["applicable", "autoUpdatesAvailable", "availableVersion", "amountOfPluginsWithUpdates", "amountOfThemesWithUpdates", "smart", "php"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InstallationUpdates from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of smart
        if self.smart:
            _dict['smart'] = self.smart.to_dict()
        # override the default output from pydantic by calling `to_dict()` of php
        if self.php:
            _dict['php'] = self.php.to_dict()
        # set to None if available_version (nullable) is None
        # and model_fields_set contains the field
        if self.available_version is None and "available_version" in self.model_fields_set:
            _dict['availableVersion'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InstallationUpdates from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "applicable": obj.get("applicable"),
            "autoUpdatesAvailable": obj.get("autoUpdatesAvailable"),
            "availableVersion": obj.get("availableVersion"),
            "amountOfPluginsWithUpdates": obj.get("amountOfPluginsWithUpdates"),
            "amountOfThemesWithUpdates": obj.get("amountOfThemesWithUpdates"),
            "smart": InstallationSmartUpdates.from_dict(obj["smart"]) if obj.get("smart") is not None else None,
            "php": InstallationSmartPhpUpdates.from_dict(obj["php"]) if obj.get("php") is not None else None
        })
        return _obj


