# coding: utf-8

"""
    WP Toolkit API

    ### REST API documentation & sandbox usage instructions  ### Initial setup  #### Plesk 1. Open 'Tools & Settings' > 'Remote API (REST)' > 'WP Toolkit REST API' 2. In the 'Servers' dropdown choose 'Public API endpoint for Plesk' 3. Specify the IP address or the hostname of your server in the 'host' field and click 'Authorize': - 3a. Provide username and password in the 'httpBasic' section, click 'Authorize', then 'Close' - 3b. Fill out the 'pleskApiToken' field, click 'Authorize', then 'Close'  #### WHM & cPanel 1. Open WP Toolkit > 'Global Settings' > 'Open REST API documentation' 2. In the 'Servers' dropdown choose 'Public API endpoint for WHM' 3. Specify the IP address or the hostname of your server in the 'host' field 4. Insert your current session identifier (in '/cpsessXXXXX' format) in the 'cpanelOrWhmSecurityToken' field. You can copy this identifier from the browser address bar 5. Click 'Authorize', provide username and password in the 'httpBasic' section, click 'Authorize', then 'Close'  **Note**: *session identifier is not required for sending external requests to WP Toolkit REST API, it is needed only for this sandbox*  ### How to perform an API request 1. Choose an API resource from the list, click on it to expand, and click 'Try it out' 2. Prefill the fields with corresponding data and click 'Execute'. If a field is not marked as requried, you can leave it empty 3. Scroll down the page to see the results of API request execution

    The version of the OpenAPI document: 6.6.5-9203
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class InstallationRestorePoint(BaseModel):
    """
    InstallationRestorePoint
    """ # noqa: E501
    available: StrictBool = Field(description="Restore point creation availability")
    restore_point_timestamp: Optional[StrictInt] = Field(description="Restore point timestamp", alias="restorePointTimestamp")
    previous_version: Optional[StrictStr] = Field(description="Source version of WordPress", alias="previousVersion")
    version: Optional[StrictStr] = Field(description="Target version of WordPress")
    error_message: Optional[StrictStr] = Field(description="Error message", alias="errorMessage")
    display_timestamp: Optional[StrictStr] = Field(description="Localized timestamp", alias="displayTimestamp")
    full_snapshot: Optional[StrictBool] = Field(description="Snapshot scope (full or partial)", alias="fullSnapshot")
    message: Optional[StrictStr] = Field(description="Tooltip message for UI")
    source_url: Optional[StrictStr] = Field(description="Source WordPress URL", alias="sourceUrl")
    __properties: ClassVar[List[str]] = ["available", "restorePointTimestamp", "previousVersion", "version", "errorMessage", "displayTimestamp", "fullSnapshot", "message", "sourceUrl"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InstallationRestorePoint from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if restore_point_timestamp (nullable) is None
        # and model_fields_set contains the field
        if self.restore_point_timestamp is None and "restore_point_timestamp" in self.model_fields_set:
            _dict['restorePointTimestamp'] = None

        # set to None if previous_version (nullable) is None
        # and model_fields_set contains the field
        if self.previous_version is None and "previous_version" in self.model_fields_set:
            _dict['previousVersion'] = None

        # set to None if version (nullable) is None
        # and model_fields_set contains the field
        if self.version is None and "version" in self.model_fields_set:
            _dict['version'] = None

        # set to None if error_message (nullable) is None
        # and model_fields_set contains the field
        if self.error_message is None and "error_message" in self.model_fields_set:
            _dict['errorMessage'] = None

        # set to None if display_timestamp (nullable) is None
        # and model_fields_set contains the field
        if self.display_timestamp is None and "display_timestamp" in self.model_fields_set:
            _dict['displayTimestamp'] = None

        # set to None if full_snapshot (nullable) is None
        # and model_fields_set contains the field
        if self.full_snapshot is None and "full_snapshot" in self.model_fields_set:
            _dict['fullSnapshot'] = None

        # set to None if message (nullable) is None
        # and model_fields_set contains the field
        if self.message is None and "message" in self.model_fields_set:
            _dict['message'] = None

        # set to None if source_url (nullable) is None
        # and model_fields_set contains the field
        if self.source_url is None and "source_url" in self.model_fields_set:
            _dict['sourceUrl'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InstallationRestorePoint from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "available": obj.get("available"),
            "restorePointTimestamp": obj.get("restorePointTimestamp"),
            "previousVersion": obj.get("previousVersion"),
            "version": obj.get("version"),
            "errorMessage": obj.get("errorMessage"),
            "displayTimestamp": obj.get("displayTimestamp"),
            "fullSnapshot": obj.get("fullSnapshot"),
            "message": obj.get("message"),
            "sourceUrl": obj.get("sourceUrl")
        })
        return _obj


