# coding: utf-8

"""
    WP Toolkit API

    ### REST API documentation & sandbox usage instructions  ### Initial setup  #### Plesk 1. Open 'Tools & Settings' > 'Remote API (REST)' > 'WP Toolkit REST API' 2. In the 'Servers' dropdown choose 'Public API endpoint for Plesk' 3. Specify the IP address or the hostname of your server in the 'host' field and click 'Authorize': - 3a. Provide username and password in the 'httpBasic' section, click 'Authorize', then 'Close' - 3b. Fill out the 'pleskApiToken' field, click 'Authorize', then 'Close'  #### WHM & cPanel 1. Open WP Toolkit > 'Global Settings' > 'Open REST API documentation' 2. In the 'Servers' dropdown choose 'Public API endpoint for WHM' 3. Specify the IP address or the hostname of your server in the 'host' field 4. Insert your current session identifier (in '/cpsessXXXXX' format) in the 'cpanelOrWhmSecurityToken' field. You can copy this identifier from the browser address bar 5. Click 'Authorize', provide username and password in the 'httpBasic' section, click 'Authorize', then 'Close'  **Note**: *session identifier is not required for sending external requests to WP Toolkit REST API, it is needed only for this sandbox*  ### How to perform an API request 1. Choose an API resource from the list, click on it to expand, and click 'Try it out' 2. Prefill the fields with corresponding data and click 'Execute'. If a field is not marked as requried, you can leave it empty 3. Scroll down the page to see the results of API request execution

    The version of the OpenAPI document: 6.6.5-9203
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from plesk_wp_toolkit_client.models.installation_domain import InstallationDomain
from plesk_wp_toolkit_client.models.installation_features import InstallationFeatures
from plesk_wp_toolkit_client.models.installation_label import InstallationLabel
from plesk_wp_toolkit_client.models.installation_owner import InstallationOwner
from plesk_wp_toolkit_client.models.installation_screenshot import InstallationScreenshot
from plesk_wp_toolkit_client.models.installation_status import InstallationStatus
from typing import Optional, Set
from typing_extensions import Self

class Installation(BaseModel):
    """
    Installation
    """ # noqa: E501
    id: StrictInt = Field(description="Installation ID in WP Toolkit database")
    title: StrictStr = Field(description="WordPress site title")
    url: StrictStr = Field(description="WordPress site URL")
    version: StrictStr = Field(description="WordPress version")
    path: StrictStr = Field(description="Local path to the WordPress site")
    labels: List[InstallationLabel]
    display_title: StrictStr = Field(description="WP Toolkit installation display title", alias="displayTitle")
    server: Optional[StrictStr] = Field(description="Server name for remote installations")
    error_message: Optional[StrictStr] = Field(description="Error message", alias="errorMessage")
    installation_type: Optional[StrictStr] = Field(description="WordPress installation type", alias="installationType")
    domain: Optional[InstallationDomain]
    screenshot: InstallationScreenshot
    owner: InstallationOwner
    features: InstallationFeatures
    status: InstallationStatus
    __properties: ClassVar[List[str]] = ["id", "title", "url", "version", "path", "labels", "displayTitle", "server", "errorMessage", "installationType", "domain", "screenshot", "owner", "features", "status"]

    @field_validator('installation_type')
    def installation_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['localPleskLinux', 'localPleskWindows', 'localCpanel', 'remoteCpanel', 'managedByPlugin', 'remoteGeneric']):
            raise ValueError("must be one of enum values ('localPleskLinux', 'localPleskWindows', 'localCpanel', 'remoteCpanel', 'managedByPlugin', 'remoteGeneric')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Installation from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in labels (list)
        _items = []
        if self.labels:
            for _item_labels in self.labels:
                if _item_labels:
                    _items.append(_item_labels.to_dict())
            _dict['labels'] = _items
        # override the default output from pydantic by calling `to_dict()` of domain
        if self.domain:
            _dict['domain'] = self.domain.to_dict()
        # override the default output from pydantic by calling `to_dict()` of screenshot
        if self.screenshot:
            _dict['screenshot'] = self.screenshot.to_dict()
        # override the default output from pydantic by calling `to_dict()` of owner
        if self.owner:
            _dict['owner'] = self.owner.to_dict()
        # override the default output from pydantic by calling `to_dict()` of features
        if self.features:
            _dict['features'] = self.features.to_dict()
        # override the default output from pydantic by calling `to_dict()` of status
        if self.status:
            _dict['status'] = self.status.to_dict()
        # set to None if server (nullable) is None
        # and model_fields_set contains the field
        if self.server is None and "server" in self.model_fields_set:
            _dict['server'] = None

        # set to None if error_message (nullable) is None
        # and model_fields_set contains the field
        if self.error_message is None and "error_message" in self.model_fields_set:
            _dict['errorMessage'] = None

        # set to None if installation_type (nullable) is None
        # and model_fields_set contains the field
        if self.installation_type is None and "installation_type" in self.model_fields_set:
            _dict['installationType'] = None

        # set to None if domain (nullable) is None
        # and model_fields_set contains the field
        if self.domain is None and "domain" in self.model_fields_set:
            _dict['domain'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Installation from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "title": obj.get("title"),
            "url": obj.get("url"),
            "version": obj.get("version"),
            "path": obj.get("path"),
            "labels": [InstallationLabel.from_dict(_item) for _item in obj["labels"]] if obj.get("labels") is not None else None,
            "displayTitle": obj.get("displayTitle"),
            "server": obj.get("server"),
            "errorMessage": obj.get("errorMessage"),
            "installationType": obj.get("installationType"),
            "domain": InstallationDomain.from_dict(obj["domain"]) if obj.get("domain") is not None else None,
            "screenshot": InstallationScreenshot.from_dict(obj["screenshot"]) if obj.get("screenshot") is not None else None,
            "owner": InstallationOwner.from_dict(obj["owner"]) if obj.get("owner") is not None else None,
            "features": InstallationFeatures.from_dict(obj["features"]) if obj.get("features") is not None else None,
            "status": InstallationStatus.from_dict(obj["status"]) if obj.get("status") is not None else None
        })
        return _obj


