# coding: utf-8

"""
    WP Toolkit API

    ### REST API documentation & sandbox usage instructions  ### Initial setup  #### Plesk 1. Open 'Tools & Settings' > 'Remote API (REST)' > 'WP Toolkit REST API' 2. In the 'Servers' dropdown choose 'Public API endpoint for Plesk' 3. Specify the IP address or the hostname of your server in the 'host' field and click 'Authorize': - 3a. Provide username and password in the 'httpBasic' section, click 'Authorize', then 'Close' - 3b. Fill out the 'pleskApiToken' field, click 'Authorize', then 'Close'  #### WHM & cPanel 1. Open WP Toolkit > 'Global Settings' > 'Open REST API documentation' 2. In the 'Servers' dropdown choose 'Public API endpoint for WHM' 3. Specify the IP address or the hostname of your server in the 'host' field 4. Insert your current session identifier (in '/cpsessXXXXX' format) in the 'cpanelOrWhmSecurityToken' field. You can copy this identifier from the browser address bar 5. Click 'Authorize', provide username and password in the 'httpBasic' section, click 'Authorize', then 'Close'  **Note**: *session identifier is not required for sending external requests to WP Toolkit REST API, it is needed only for this sandbox*  ### How to perform an API request 1. Choose an API resource from the list, click on it to expand, and click 'Try it out' 2. Prefill the fields with corresponding data and click 'Execute'. If a field is not marked as requried, you can leave it empty 3. Scroll down the page to see the results of API request execution

    The version of the OpenAPI document: 6.6.5-9203
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from plesk_wp_toolkit_client.models.setup_drawer_settings_response_languages_item import SetupDrawerSettingsResponseLanguagesItem
from plesk_wp_toolkit_client.models.setup_drawer_settings_response_logins_item import SetupDrawerSettingsResponseLoginsItem
from typing import Optional, Set
from typing_extensions import Self

class SetupDrawerSettingsResponse(BaseModel):
    """
    SetupDrawerSettingsResponse
    """ # noqa: E501
    login_url: Optional[StrictStr] = Field(description="Login URL to WordPress admin dashboard", alias="loginUrl")
    current_login: Optional[StrictStr] = Field(description="Site administrator username for WordPress admin dashboard", alias="currentLogin")
    current_password: Optional[StrictStr] = Field(description="Site administrator password for WordPress admin dashboard", alias="currentPassword")
    current_email: Optional[StrictStr] = Field(description="Site administrator email", alias="currentEmail")
    current_language: Optional[StrictStr] = Field(description="Installation language", alias="currentLanguage")
    available_logins: List[SetupDrawerSettingsResponseLoginsItem] = Field(description="List of available administrator accounts", alias="availableLogins")
    available_languages: List[SetupDrawerSettingsResponseLanguagesItem] = Field(description="List of available languages", alias="availableLanguages")
    __properties: ClassVar[List[str]] = ["loginUrl", "currentLogin", "currentPassword", "currentEmail", "currentLanguage", "availableLogins", "availableLanguages"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SetupDrawerSettingsResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in available_logins (list)
        _items = []
        if self.available_logins:
            for _item_available_logins in self.available_logins:
                if _item_available_logins:
                    _items.append(_item_available_logins.to_dict())
            _dict['availableLogins'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in available_languages (list)
        _items = []
        if self.available_languages:
            for _item_available_languages in self.available_languages:
                if _item_available_languages:
                    _items.append(_item_available_languages.to_dict())
            _dict['availableLanguages'] = _items
        # set to None if login_url (nullable) is None
        # and model_fields_set contains the field
        if self.login_url is None and "login_url" in self.model_fields_set:
            _dict['loginUrl'] = None

        # set to None if current_login (nullable) is None
        # and model_fields_set contains the field
        if self.current_login is None and "current_login" in self.model_fields_set:
            _dict['currentLogin'] = None

        # set to None if current_password (nullable) is None
        # and model_fields_set contains the field
        if self.current_password is None and "current_password" in self.model_fields_set:
            _dict['currentPassword'] = None

        # set to None if current_email (nullable) is None
        # and model_fields_set contains the field
        if self.current_email is None and "current_email" in self.model_fields_set:
            _dict['currentEmail'] = None

        # set to None if current_language (nullable) is None
        # and model_fields_set contains the field
        if self.current_language is None and "current_language" in self.model_fields_set:
            _dict['currentLanguage'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SetupDrawerSettingsResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "loginUrl": obj.get("loginUrl"),
            "currentLogin": obj.get("currentLogin"),
            "currentPassword": obj.get("currentPassword"),
            "currentEmail": obj.get("currentEmail"),
            "currentLanguage": obj.get("currentLanguage"),
            "availableLogins": [SetupDrawerSettingsResponseLoginsItem.from_dict(_item) for _item in obj["availableLogins"]] if obj.get("availableLogins") is not None else None,
            "availableLanguages": [SetupDrawerSettingsResponseLanguagesItem.from_dict(_item) for _item in obj["availableLanguages"]] if obj.get("availableLanguages") is not None else None
        })
        return _obj


