# coding: utf-8

"""
    WP Toolkit API

    ### REST API documentation & sandbox usage instructions  ### Initial setup  #### Plesk 1. Open 'Tools & Settings' > 'Remote API (REST)' > 'WP Toolkit REST API' 2. In the 'Servers' dropdown choose 'Public API endpoint for Plesk' 3. Specify the IP address or the hostname of your server in the 'host' field and click 'Authorize': - 3a. Provide username and password in the 'httpBasic' section, click 'Authorize', then 'Close' - 3b. Fill out the 'pleskApiToken' field, click 'Authorize', then 'Close'  #### WHM & cPanel 1. Open WP Toolkit > 'Global Settings' > 'Open REST API documentation' 2. In the 'Servers' dropdown choose 'Public API endpoint for WHM' 3. Specify the IP address or the hostname of your server in the 'host' field 4. Insert your current session identifier (in '/cpsessXXXXX' format) in the 'cpanelOrWhmSecurityToken' field. You can copy this identifier from the browser address bar 5. Click 'Authorize', provide username and password in the 'httpBasic' section, click 'Authorize', then 'Close'  **Note**: *session identifier is not required for sending external requests to WP Toolkit REST API, it is needed only for this sandbox*  ### How to perform an API request 1. Choose an API resource from the list, click on it to expand, and click 'Try it out' 2. Prefill the fields with corresponding data and click 'Execute'. If a field is not marked as requried, you can leave it empty 3. Scroll down the page to see the results of API request execution

    The version of the OpenAPI document: 6.6.5-9203
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from plesk_wp_toolkit_client.models.installation_auto_update_response import InstallationAutoUpdateResponse
from plesk_wp_toolkit_client.models.installation_plugin import InstallationPlugin
from plesk_wp_toolkit_client.models.installation_theme import InstallationTheme
from plesk_wp_toolkit_client.models.word_press_updates_response_core import WordPressUpdatesResponseCore
from plesk_wp_toolkit_client.models.word_press_updates_response_tasks import WordPressUpdatesResponseTasks
from plesk_wp_toolkit_client.models.word_press_updates_smart_updates_response import WordPressUpdatesSmartUpdatesResponse
from typing import Optional, Set
from typing_extensions import Self

class WordPressUpdatesResponse(BaseModel):
    """
    WordPressUpdatesResponse
    """ # noqa: E501
    id: Union[StrictFloat, StrictInt]
    applicable: StrictBool
    display_title: StrictStr = Field(alias="displayTitle")
    title: StrictStr
    multisite: StrictBool
    vulnerable: Optional[StrictBool]
    last_check_update_timestamp: Optional[StrictInt] = Field(alias="lastCheckUpdateTimestamp")
    smart_update: WordPressUpdatesSmartUpdatesResponse = Field(alias="smartUpdate")
    core: WordPressUpdatesResponseCore
    plugins: List[InstallationPlugin]
    themes: List[InstallationTheme]
    auto_update: InstallationAutoUpdateResponse = Field(alias="autoUpdate")
    tasks: WordPressUpdatesResponseTasks
    __properties: ClassVar[List[str]] = ["id", "applicable", "displayTitle", "title", "multisite", "vulnerable", "lastCheckUpdateTimestamp", "smartUpdate", "core", "plugins", "themes", "autoUpdate", "tasks"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WordPressUpdatesResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of smart_update
        if self.smart_update:
            _dict['smartUpdate'] = self.smart_update.to_dict()
        # override the default output from pydantic by calling `to_dict()` of core
        if self.core:
            _dict['core'] = self.core.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in plugins (list)
        _items = []
        if self.plugins:
            for _item_plugins in self.plugins:
                if _item_plugins:
                    _items.append(_item_plugins.to_dict())
            _dict['plugins'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in themes (list)
        _items = []
        if self.themes:
            for _item_themes in self.themes:
                if _item_themes:
                    _items.append(_item_themes.to_dict())
            _dict['themes'] = _items
        # override the default output from pydantic by calling `to_dict()` of auto_update
        if self.auto_update:
            _dict['autoUpdate'] = self.auto_update.to_dict()
        # override the default output from pydantic by calling `to_dict()` of tasks
        if self.tasks:
            _dict['tasks'] = self.tasks.to_dict()
        # set to None if vulnerable (nullable) is None
        # and model_fields_set contains the field
        if self.vulnerable is None and "vulnerable" in self.model_fields_set:
            _dict['vulnerable'] = None

        # set to None if last_check_update_timestamp (nullable) is None
        # and model_fields_set contains the field
        if self.last_check_update_timestamp is None and "last_check_update_timestamp" in self.model_fields_set:
            _dict['lastCheckUpdateTimestamp'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WordPressUpdatesResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "applicable": obj.get("applicable"),
            "displayTitle": obj.get("displayTitle"),
            "title": obj.get("title"),
            "multisite": obj.get("multisite"),
            "vulnerable": obj.get("vulnerable"),
            "lastCheckUpdateTimestamp": obj.get("lastCheckUpdateTimestamp"),
            "smartUpdate": WordPressUpdatesSmartUpdatesResponse.from_dict(obj["smartUpdate"]) if obj.get("smartUpdate") is not None else None,
            "core": WordPressUpdatesResponseCore.from_dict(obj["core"]) if obj.get("core") is not None else None,
            "plugins": [InstallationPlugin.from_dict(_item) for _item in obj["plugins"]] if obj.get("plugins") is not None else None,
            "themes": [InstallationTheme.from_dict(_item) for _item in obj["themes"]] if obj.get("themes") is not None else None,
            "autoUpdate": InstallationAutoUpdateResponse.from_dict(obj["autoUpdate"]) if obj.get("autoUpdate") is not None else None,
            "tasks": WordPressUpdatesResponseTasks.from_dict(obj["tasks"]) if obj.get("tasks") is not None else None
        })
        return _obj


