# coding: utf-8

"""
    WP Toolkit API

    ### REST API documentation & sandbox usage instructions  ### Initial setup  #### Plesk 1. Open 'Tools & Settings' > 'Remote API (REST)' > 'WP Toolkit REST API' 2. In the 'Servers' dropdown choose 'Public API endpoint for Plesk' 3. Specify the IP address or the hostname of your server in the 'host' field and click 'Authorize': - 3a. Provide username and password in the 'httpBasic' section, click 'Authorize', then 'Close' - 3b. Fill out the 'pleskApiToken' field, click 'Authorize', then 'Close'  #### WHM & cPanel 1. Open WP Toolkit > 'Global Settings' > 'Open REST API documentation' 2. In the 'Servers' dropdown choose 'Public API endpoint for WHM' 3. Specify the IP address or the hostname of your server in the 'host' field 4. Insert your current session identifier (in '/cpsessXXXXX' format) in the 'cpanelOrWhmSecurityToken' field. You can copy this identifier from the browser address bar 5. Click 'Authorize', provide username and password in the 'httpBasic' section, click 'Authorize', then 'Close'  **Note**: *session identifier is not required for sending external requests to WP Toolkit REST API, it is needed only for this sandbox*  ### How to perform an API request 1. Choose an API resource from the list, click on it to expand, and click 'Try it out' 2. Prefill the fields with corresponding data and click 'Execute'. If a field is not marked as requried, you can leave it empty 3. Scroll down the page to see the results of API request execution

    The version of the OpenAPI document: 6.6.5-9203
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from plesk_wp_toolkit_client.models.word_press_asset_author import WordPressAssetAuthor
from plesk_wp_toolkit_client.models.word_press_asset_rating import WordPressAssetRating
from plesk_wp_toolkit_client.models.word_press_asset_screenshots_inner import WordPressAssetScreenshotsInner
from plesk_wp_toolkit_client.models.word_press_asset_section import WordPressAssetSection
from typing import Optional, Set
from typing_extensions import Self

class WordPressAsset(BaseModel):
    """
    WordPressAsset
    """ # noqa: E501
    author: WordPressAssetAuthor
    downloaded: StrictInt = Field(description="Number of downloads")
    installed: StrictBool = Field(description="Asset is installed or not")
    logo_url: StrictStr = Field(description="URL to a WordPress logo", alias="logoUrl")
    preview_url: StrictStr = Field(description="URL to a preview page", alias="previewUrl")
    rating: WordPressAssetRating
    requires: StrictStr = Field(description="Required WordPress version")
    screenshot_url: StrictStr = Field(description="URL to an asset icon or screenshot", alias="screenshotUrl")
    screenshots: List[WordPressAssetScreenshotsInner]
    short_description: StrictStr = Field(description="Asset description", alias="shortDescription")
    sections: List[WordPressAssetSection]
    slug: StrictStr = Field(description="Asset slug")
    tested: Optional[StrictStr] = Field(description="Tested WordPress version")
    title: StrictStr = Field(description="Asset name")
    updated: Optional[StrictStr] = Field(description="Last update date")
    version: StrictStr = Field(description="Asset version")
    __properties: ClassVar[List[str]] = ["author", "downloaded", "installed", "logoUrl", "previewUrl", "rating", "requires", "screenshotUrl", "screenshots", "shortDescription", "sections", "slug", "tested", "title", "updated", "version"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WordPressAsset from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of author
        if self.author:
            _dict['author'] = self.author.to_dict()
        # override the default output from pydantic by calling `to_dict()` of rating
        if self.rating:
            _dict['rating'] = self.rating.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in screenshots (list)
        _items = []
        if self.screenshots:
            for _item_screenshots in self.screenshots:
                if _item_screenshots:
                    _items.append(_item_screenshots.to_dict())
            _dict['screenshots'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in sections (list)
        _items = []
        if self.sections:
            for _item_sections in self.sections:
                if _item_sections:
                    _items.append(_item_sections.to_dict())
            _dict['sections'] = _items
        # set to None if tested (nullable) is None
        # and model_fields_set contains the field
        if self.tested is None and "tested" in self.model_fields_set:
            _dict['tested'] = None

        # set to None if updated (nullable) is None
        # and model_fields_set contains the field
        if self.updated is None and "updated" in self.model_fields_set:
            _dict['updated'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WordPressAsset from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "author": WordPressAssetAuthor.from_dict(obj["author"]) if obj.get("author") is not None else None,
            "downloaded": obj.get("downloaded"),
            "installed": obj.get("installed"),
            "logoUrl": obj.get("logoUrl"),
            "previewUrl": obj.get("previewUrl"),
            "rating": WordPressAssetRating.from_dict(obj["rating"]) if obj.get("rating") is not None else None,
            "requires": obj.get("requires"),
            "screenshotUrl": obj.get("screenshotUrl"),
            "screenshots": [WordPressAssetScreenshotsInner.from_dict(_item) for _item in obj["screenshots"]] if obj.get("screenshots") is not None else None,
            "shortDescription": obj.get("shortDescription"),
            "sections": [WordPressAssetSection.from_dict(_item) for _item in obj["sections"]] if obj.get("sections") is not None else None,
            "slug": obj.get("slug"),
            "tested": obj.get("tested"),
            "title": obj.get("title"),
            "updated": obj.get("updated"),
            "version": obj.get("version")
        })
        return _obj


